# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('userMessage', models.CharField(max_length=255)),
                ('createDate', models.DateField()),
                ('payDate', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('confirmDate', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subTitle', models.CharField(max_length=255)),
                ('orignalPrice', models.FloatField()),
                ('promotePrice', models.FloatField()),
                ('stock', models.IntegerField()),
                ('createDate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Productimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Propertyvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
                ('ptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4000)),
                ('createDate', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('isadmin', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
